<?php

/**
 * @file
 * local_actions.theme
 */

use Drupal\gin\GinSettings;

/**
 * Local actions preprocess.
 */
function gin_preprocess_menu_local_action(&$variables) {
  // Are we displaying an edit form?
  if (_gin_form_actions()) {
    $classes = &$variables['link']['#options']['attributes']['class'];
    $classes = array_filter($classes, function ($e) {
      return $e != 'button--primary';
    });
  }

  // Get theme settings.
  $settings = \Drupal::classResolver(GinSettings::class);
  $bundle_select = $settings->get('bundle_select');
  $routeName = $variables['link']['#url']->getRouteName();

  // Modal variant.
  if ($bundle_select === 'modal') {
    if ($routeName === 'node.add_page' || $routeName === 'entity.media.add_page') {
      $variables['link']['#options']['attributes']['class'][] = 'use-ajax';
      $variables['link']['#options']['attributes']['data-dialog-type'] = 'modal';
      $variables['link']['#options']['attributes']['data-dialog-options'] = '{ "width": "800px", "dialogClass": "gin--add-modal" }';
    }
  }
  // Dropbutton variant.
  elseif ($bundle_select === 'drop') {
    // Dropbutton variant code.
  }
}
